### ISSUE TITLE
Windows build

### ISSUE THREAD

**Issue by duncanwp** [conda-forge/pyhdf-feedstock#16]
I see that Windows support has been dropped for this build but I can't find an associated issue - what was the rationale? I have a package which depends on it and I just noticed it was missing. 

The HDF4 build still seems to support Windows so it would be great to try and fix whatever the issue was.

**Comment by duncanwp** [comment]
Ping @ocefpaf

**Comment by ocefpaf** [comment]
> The HDF4 build still seems to support Windows so it would be great to try and fix whatever the issue was.

I recall having issues with the Windows builds. If you know how to get those builds working again please send a PR.

**Comment by fhs** [comment]
Do we want to provide 32-bit Windows support as well? At some point, v0.9.0 for win-32 was uploaded to conda-forge and it's stuck at that version: https://anaconda.org/conda-forge/pyhdf

**Comment by ocefpaf** [comment]
Conda-forge dropped support for win-32 a while back. All wib-32 packages
are outdated.
