### ISSUE TITLE
Update to point to PyPI package

### ISSUE THREAD

**Issue by djhoese** [conda-forge/pyhdf-feedstock#18]
As per https://github.com/pypa/warehouse/issues/5157 the ownership of the PyPI package for pyhdf has been transferred to @fhs and the https://github.com/fhs/pyhdf repository. This was previously the `python-hdf4` package and was the original basis for HDF-EOS version of the package that is currently used for this conda-forge package. See https://github.com/fhs/pyhdf/issues/13 for details on this whole ownership conversation. Given the ownership change `python-hdf4` has been renamed to `pyhdf`. It is now the official pyhdf replacement.

Would it be possible to add @fhs as a maintainer to this recipe? Assuming they want to be. Otherwise I am willing to be a maintainer.

**Comment by djhoese** [comment]
Ah I should have mentioned @hdfeos explicitly too.

**Comment by fhs** [comment]
I don't use conda and not very familiar with it either, so I'm happy with @djhoese or the current maintainer continuing to maintain the conda recipe.

**Comment by ocefpaf** [comment]
I put up a PR in #20 

@fhs do you have any advice for us to get the Windows builds going?

Our `hdf4` on Windows is https://anaconda.org/conda-forge/hdf4/4.2.13/download/win-64/hdf4-4.2.13-hf8e6fe8_1002.tar.bz2

 and if you check [bld.bat](https://github.com/conda-forge/pyhdf-feedstock/pull/20) file in the PR you'll notice that we have some environmental variables to access library and in include dirs, but everything I tried failed.

**Comment by fhs** [comment]
@ocefpaf Windows is basically untested by me, but I have some ideas on what might be going wrong. I'll reply to the PR.

**Comment by ocefpaf** [comment]
> @ocefpaf Windows is basically untested by me, but I have some ideas on what might be going wrong. I'll reply to the PR.

Thanks!
