### ISSUE TITLE
pyhdf v0.10.1

### ISSUE THREAD

**Issue by fhs** [conda-forge/pyhdf-feedstock#22]
I've released v0.10.1. All the Windows workarounds can be removed.

**Comment by ocefpaf** [comment]
> I've released v0.10.1. All the Windows workarounds can be removed.

Thanks @fhs! Is that on PyPI and/or GitHub? The bot should pick new releases automatically if they are published on PyPI under the URL in https://github.com/conda-forge/pyhdf-feedstock/blob/master/recipe/meta.yaml#L8.

**Comment by djhoese** [comment]
As mentioned on gitter, the auto bot seems to have died.

**Comment by ocefpaf** [comment]
Working on it. (But nothing prevents us to send a manual update here if you are in a hurry.)
