### ISSUE TITLE
python 3.7 support

### ISSUE THREAD

**Issue by mikapfl** [conda-forge/pyhdf-feedstock#9]
Hi,

it would be great to have a python 3.7 version of pyhdf available from conda-forge. I'd be willing to somehow help in providing that, but I couldn't really find info what is missing. Does the continuos integration need to be poked to build it or something?

Cheers

Mika

**Comment by ocefpaf** [comment]
@mikapfl conda-forge is not build Python 3.7 packages yet but that will happen soon in an automated PR. I'm closing this b/c there is not much we can do now. Hang on tide and keep tuned on the changes here in the near future.

**Comment by mikapfl** [comment]
Okay, thanks for the info! (-:
